### ISSUE TITLE
To add to the README, maybe?

### ISSUE THREAD

**Issue by paul-hammant** [AppJail-makejails/ubuntu#1]
In a section before `appjail makejail -j ubuntu ....` the user might be wanting to run these commands:

```
pkg install debootstrap
appjail fetch debootstrap jammy
```

It seemed to get me though a blocker, and might be a small improvement to an otherwise excellent README

**Comment by DtxdF** [comment]
When writing a new Makejail, and of course its README, the writer must assume a few things:

* The user has knowledge of FreeBSD.
* The user has some knowledge of the POSIX shell (`/bin/sh`).
* The user reads the AppJail documentation, at least the part that interests him, so he must know what to install or configure to perform a given task.

I wrote the documentation for that and I am currently writing the manpages to give more detaila about a given task, so if I write again one thing that the user should know, [I'm repeating myself](https://en.m.wikipedia.org/wiki/Don%27t_repeat_yourself).

**Comment by DtxdF** [comment]
This issue has been closed due to inactivity. You can reopen it if you wish.
